apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: pod-reader
rules:
  - apiGroups: ['']   # '' == core api group
    resources: ['pods']
    verbs: ['get', 'list']