apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-inside-dev
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: db-config
            mountPath: /db/db-config
      volumes:      # same level as containers
        - name: db-config   # name of vol
          configMap:
            name: db-init-config      # match name of the configMap generated
    