apiVersion: v1
kind: Pod
metadata:
  name: color-api
  labels:
    app: color-api
spec:
  containers:
  - name: color-api
    image: kyleetrata/color-api:1.2.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: DELAY_STARTUP
        value: 'false'
      - name: FAIL_LIVENESS 
        value: 'true'
    startupProbe:
      httpGet:
        path: /up
        port: 80
      failureThreshold: 2   # number of times the startup probe can fail
      periodSeconds: 3
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      failureThreshold: 3
      periodSeconds: 10