apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/local1 # path must exist in the node
  nodeAffinity:   # ensure that pods that use this volume are scheduled in the node that has this vol
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ['minikube']
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-vol-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: local-vol-pod
  labels:
    app: local-vol-pod
spec: 
  containers:
  - name: local-vol
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      - 'sleep 3600'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: local-vol
        mountPath: /mnt/local
  volumes:
    - name: local-vol
      persistentVolumeClaim:
        claimName: local-vol-claim
---
apiVersion: v1
kind: Pod
metadata:
  name: local-vol-pod2
  labels:
    app: local-vol-pod2
spec: 
  containers:
  - name: local-vol
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      - 'sleep 3600'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: local-vol
        mountPath: /mnt/local2
  volumes:
    - name: local-vol
      persistentVolumeClaim:
        claimName: local-vol-claim

