services:
  notes:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 3001:80
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTES_USER}:${NOTES_PASSWORD}@notes-db/${NOTES_DB}
    env_file:
      - .env
    networks:
      - notes-net
    depends_on:
      - notes-db
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
  notes-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      # - './db-config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
      - type: volume
        source: notes-data
        target: /data/db
    networks:
      - notes-net

volumes:
  notes-data:

networks:
  notes-net: