# ==== VANILLA JS SETUP ====
# FROM node:22
# WORKDIR /app
# COPY package*.json .
# RUN npm ci

# COPY index.js index.js

# CMD ["node", "index.js"]
# ==== END VANILLA JS ====


# ==== SMALLER BASE IMAGE ====
FROM node:22-alpine
WORKDIR /app
COPY package*.json .
RUN npm ci

COPY index.js index.js

CMD ["node", "index.js"]