apiVersion: v1
kind: Pod
metadata:
  name: color-api
  namespace: dev
  labels:
    app: color-api
spec:
  containers:
  - name: color-api
    image: kyleetrata/color-api:1.1.1
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    ports:
      - containerPort: 80
