# 1. Build production bundle
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

# 2. Serve production bundle with HTTP server
FROM nginx:1.27.0
COPY --from=build /app/build /usr/share/nginx/html

# Replace default nginx config with SPA-aware config
COPY nginx.conf /etc/nginx/conf.d/default.conf