include:
  - notebooks-back/compose.yaml
  - notes-back/compose.yaml

services:
  reverse-proxy:
    image: nginx:1.27.0
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - notebooks
      - notes
    networks:
      - notes-app-net

networks:
  notes-app-net: