apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app.kubernetes.io/name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      - 'echo "$DB_USER" && echo "$DB_PASSWORD" && sleep 1800'
    volumeMounts:
      - name: db-secrets
        mountPath: /etc/db    
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: db-secrets
      secret:
        secretName: db-creds
        items:
          - key: password
            path: dev/password
