apiVersion: v1
kind: Service
metadata:
  name: color-api-svc
  labels:
    app: color-api
spec:
  type: ClusterIP     # ClusterIP is the default type
  selector:
    app: color-api
  ports:
  - port: 80
    targetPort: 80
