apiVersion: v1
kind: Service
metadata:
  name: color-svc
spec:
  type: NodePort
  selector:
    app: color-api    # match metadata.labels of color-api pods
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
