apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: mongodb
spec:
  clusterIP: None     # Headless svc
  selector:
    app: mongodb    
  ports:
  - port: 27017
    targetPort: 27017
